//! Compare two schemas and write the SQL that makes `dst` look like `src`.
//! Destructive steps (dropping tables or columns) are written commented out.

use crate::model::{Column, Table, TableKind};
use crate::sql::Dialect;
use std::collections::BTreeMap;

#[derive(Debug, Default, PartialEq)]
pub struct Diff {
    /// Tables only in `src` (name -> table).
    pub create: Vec<Table>,
    /// Tables only in `dst`.
    pub drop: Vec<Table>,
    /// (dst table, src column) missing in dst.
    pub add_cols: Vec<(Table, Column)>,
    /// (dst table, dst column) not in src.
    pub drop_cols: Vec<(Table, Column)>,
    /// (dst table, src column, dst column) where the definitions differ.
    pub alter_cols: Vec<(Table, Column, Column)>,
}

impl Diff {
    pub fn is_empty(&self) -> bool {
        *self == Diff::default()
    }
}

/// Sequence-backed defaults (`nextval(...)`) are ignored: the sequence would have to exist on the target.
fn defaults_differ(a: &Option<String>, b: &Option<String>) -> bool {
    let seq = |d: &Option<String>| d.as_deref().is_some_and(|x| x.contains("nextval("));
    if seq(a) || seq(b) {
        return false;
    }
    a != b
}

fn by_name(tables: &[Table]) -> BTreeMap<String, &Table> {
    tables.iter().filter(|t| t.kind == TableKind::Table).map(|t| (t.name.clone(), t)).collect()
}

pub fn diff(src: &[Table], dst: &[Table]) -> Diff {
    let (s, d) = (by_name(src), by_name(dst));
    let mut out = Diff::default();
    for (name, t) in &s {
        let Some(dt) = d.get(name) else {
            out.create.push((*t).clone());
            continue;
        };
        for sc in &t.columns {
            match dt.columns.iter().find(|c| c.name == sc.name) {
                None => out.add_cols.push(((*dt).clone(), sc.clone())),
                Some(dc) if dc.type_name != sc.type_name || dc.nullable != sc.nullable || defaults_differ(&sc.default, &dc.default) => {
                    out.alter_cols.push(((*dt).clone(), sc.clone(), dc.clone()))
                }
                _ => {}
            }
        }
        for dc in &dt.columns {
            if !t.columns.iter().any(|c| c.name == dc.name) {
                out.drop_cols.push(((*dt).clone(), dc.clone()));
            }
        }
    }
    for (name, t) in &d {
        if !s.contains_key(name) {
            out.drop.push((*t).clone());
        }
    }
    out
}

fn qualified(d: Dialect, t: &Table) -> String {
    if t.schema.is_empty() {
        d.quote(&t.name)
    } else {
        format!("{}.{}", d.quote(&t.schema), d.quote(&t.name))
    }
}

fn definition(c: &Column) -> String {
    let mut s = c.type_name.clone();
    if !c.nullable {
        s.push_str(" NOT NULL");
    }
    if let Some(def) = &c.default {
        s.push_str(&format!(" DEFAULT {def}"));
    }
    s
}

/// `create_ddl` supplies the CREATE statement for a table that only exists in `src`.
pub fn render(diff: &Diff, d: Dialect, create_ddl: &dyn Fn(&Table) -> String) -> String {
    if diff.is_empty() {
        return "-- The schemas already match.\n".into();
    }
    let mut out = String::from("-- Generated by dboard: run on the target connection to make its schema match the source.\n-- Review before running. Destructive statements are commented out.\n\n");
    for t in &diff.create {
        let ddl = create_ddl(t);
        let note = if ddl.contains("nextval(") { "-- NOTE: uses sequence defaults; create those sequences on the target first.\n" } else { "" };
        out.push_str(&format!("-- new table {}\n{note}{}\n\n", t.name, ddl.trim_end()));
    }
    for (t, c) in &diff.add_cols {
        out.push_str(&format!("ALTER TABLE {} ADD COLUMN {} {};\n", qualified(d, t), d.quote(&c.name), definition(c)));
    }
    for (t, sc, dc) in &diff.alter_cols {
        let q = qualified(d, t);
        match d {
            Dialect::Pg => {
                if sc.type_name != dc.type_name {
                    out.push_str(&format!("ALTER TABLE {q} ALTER COLUMN {} TYPE {};\n", d.quote(&sc.name), sc.type_name));
                }
                if sc.nullable != dc.nullable {
                    out.push_str(&format!("ALTER TABLE {q} ALTER COLUMN {} {} NOT NULL;\n", d.quote(&sc.name), if sc.nullable { "DROP" } else { "SET" }));
                }
                if defaults_differ(&sc.default, &dc.default) {
                    match &sc.default {
                        Some(def) => out.push_str(&format!("ALTER TABLE {q} ALTER COLUMN {} SET DEFAULT {def};\n", d.quote(&sc.name))),
                        None => out.push_str(&format!("ALTER TABLE {q} ALTER COLUMN {} DROP DEFAULT;\n", d.quote(&sc.name))),
                    }
                }
            }
            Dialect::My => out.push_str(&format!("ALTER TABLE {q} MODIFY COLUMN {} {};\n", d.quote(&sc.name), definition(sc))),
        }
    }
    if !diff.drop_cols.is_empty() || !diff.drop.is_empty() {
        out.push_str("\n-- Only in the target (uncomment to remove):\n");
    }
    for (t, c) in &diff.drop_cols {
        out.push_str(&format!("-- ALTER TABLE {} DROP COLUMN {};\n", qualified(d, t), d.quote(&c.name)));
    }
    for t in &diff.drop {
        out.push_str(&format!("-- DROP TABLE {};\n", qualified(d, t)));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn col(name: &str, ty: &str, nullable: bool) -> Column {
        Column { name: name.into(), type_name: ty.into(), nullable, is_primary_key: false, default: None, fk: None }
    }
    fn table(name: &str, cols: Vec<Column>) -> Table {
        Table { schema: "public".into(), name: name.into(), kind: TableKind::Table, columns: cols, estimated_rows: None, size_bytes: None, indexes: vec![], keyless_edit: false }
    }

    #[test]
    fn finds_every_kind_of_difference() {
        let src = vec![table("users", vec![col("id", "integer", false), col("email", "text", true), col("age", "bigint", true)]), table("new_t", vec![col("x", "int", true)])];
        let dst = vec![table("users", vec![col("id", "integer", false), col("age", "integer", true), col("old", "text", true)]), table("legacy", vec![col("y", "int", true)])];
        let d = diff(&src, &dst);
        assert_eq!(d.create.len(), 1);
        assert_eq!(d.drop.len(), 1);
        assert_eq!(d.add_cols.len(), 1);
        assert_eq!(d.drop_cols.len(), 1);
        assert_eq!(d.alter_cols.len(), 1);
    }

    #[test]
    fn renders_postgres_and_comments_out_destructive_steps() {
        let src = vec![table("users", vec![col("id", "integer", false), col("email", "text", false)])];
        let dst = vec![table("users", vec![col("id", "integer", false), col("old", "text", true)]), table("legacy", vec![])];
        let sql = render(&diff(&src, &dst), Dialect::Pg, &|t| format!("CREATE TABLE {} ();", t.name));
        assert!(sql.contains("ALTER TABLE \"public\".\"users\" ADD COLUMN \"email\" text NOT NULL;"));
        assert!(sql.contains("-- ALTER TABLE \"public\".\"users\" DROP COLUMN \"old\";"));
        assert!(sql.contains("-- DROP TABLE \"public\".\"legacy\";"));
        assert!(!sql.lines().any(|l| l.starts_with("DROP") || l.starts_with("ALTER TABLE \"public\".\"users\" DROP")));
    }

    #[test]
    fn sequence_defaults_are_not_treated_as_changes() {
        let mut a = col("id", "integer", false);
        a.default = Some("nextval('t_id_seq'::regclass)".into());
        let src = vec![table("t", vec![a])];
        let dst = vec![table("t", vec![col("id", "integer", false)])];
        assert!(diff(&src, &dst).is_empty());
    }

    #[test]
    fn identical_schemas_say_so() {
        let s = vec![table("a", vec![col("x", "int", true)])];
        assert!(diff(&s, &s).is_empty());
        assert!(render(&diff(&s, &s), Dialect::Pg, &|_| String::new()).contains("already match"));
    }

    #[test]
    fn mysql_uses_modify_column() {
        let src = vec![table("t", vec![col("a", "bigint", false)])];
        let dst = vec![table("t", vec![col("a", "int", true)])];
        let sql = render(&diff(&src, &dst), Dialect::My, &|_| String::new());
        assert!(sql.contains("MODIFY COLUMN `a` bigint NOT NULL;"));
    }
}
